###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: borgert-redis

    mysql:
      image: mysql:5.7
      container_name: borgert-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=habbit
        - MYSQL_DATABASE=borgert
        - MYSQL_USER=borgert
        - MYSQL_PASSWORD=borgert
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: borgert-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: borgert-php-fpm
      working_dir: /application
      env_file:
        - .env
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

